In [3]:
import numpy as np

ar=np.array([1,2,8,9,10,11])

print(ar)

print(type(ar))

[ 1  2  8  9 10 11]
<class 'numpy.ndarray'>


In [4]:
ar2=np.array([[1,2,3,4],[4,5,6,7]])

print(ar2)

[[1 2 3 4]
 [4 5 6 7]]


In [7]:
list1=[1,2,4,7,8]
list2=[2,5,6,7,9]

prod=list(map(lambda x,y:x*y ,list1,list2))

prod

[2, 10, 24, 49, 72]

In [8]:
arr1=np.array(list1)
arr2=np.array(list2)

pr=arr1*arr2
print(pr)

[ 2 10 24 49 72]


In [12]:
sq_list=[i**2 for i in list1]

sq=arr1**2

sq

array([ 1,  4, 16, 49, 64], dtype=int32)

In [14]:
np.ones([3,5],dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
np.zeros([6,4],dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [20]:
np.random.random([5,5])

array([[0.42365604, 0.20399105, 0.78434   , 0.71029448, 0.48993425],
       [0.2207626 , 0.73589193, 0.65938935, 0.31740342, 0.9549844 ],
       [0.77624091, 0.13461087, 0.43481863, 0.54709587, 0.70400688],
       [0.90091897, 0.63180301, 0.1508393 , 0.62082429, 0.59889904],
       [0.70281009, 0.54109325, 0.8979225 , 0.72075285, 0.36870845]])

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [31]:
np.full([4,5],20)

array([[20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20]])

In [32]:
np.tile([1,2,3],3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [33]:
np.tile([1,4,7],[2,3])

array([[1, 4, 7, 1, 4, 7, 1, 4, 7],
       [1, 4, 7, 1, 4, 7, 1, 4, 7]])

In [34]:
np.tile([1,4,7],(2,3))

array([[1, 4, 7, 1, 4, 7, 1, 4, 7],
       [1, 4, 7, 1, 4, 7, 1, 4, 7]])

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [38]:
np.random.random([3,4])

array([[0.85354301, 0.20898775, 0.91576165, 0.29599977],
       [0.85979605, 0.71669567, 0.69678502, 0.57652481],
       [0.0652904 , 0.75478617, 0.54961914, 0.80528193]])

In [39]:
np.random.randint(1,10,(3,3))

array([[7, 1, 9],
       [6, 1, 3],
       [4, 2, 2]])

In [41]:
n=np.random.random([10,20])
n

array([[0.75169874, 0.39145535, 0.08922585, 0.34817459, 0.30059482,
        0.40937897, 0.99515197, 0.9142776 , 0.30457164, 0.25607044,
        0.01411641, 0.67116502, 0.81531542, 0.51713531, 0.23164978,
        0.83768828, 0.24722603, 0.52308703, 0.50871181, 0.49643992],
       [0.71540261, 0.29437528, 0.45055665, 0.248158  , 0.30937339,
        0.58837265, 0.2524866 , 0.72642645, 0.70219693, 0.24579202,
        0.20515034, 0.88857035, 0.58617237, 0.70461489, 0.42314287,
        0.29773612, 0.97615571, 0.97482915, 0.36153179, 0.68467507],
       [0.9455657 , 0.59985062, 0.38504234, 0.37380749, 0.16099269,
        0.45022305, 0.83971467, 0.35140443, 0.1176855 , 0.0422357 ,
        0.15340173, 0.80287102, 0.05290942, 0.62679974, 0.61112785,
        0.20068164, 0.12152354, 0.76763385, 0.62138789, 0.20018121],
       [0.84866188, 0.95371423, 0.74302258, 0.53417713, 0.24845574,
        0.08240086, 0.03662599, 0.67715697, 0.73277146, 0.64730188,
        0.00762158, 0.44805399, 0.56140694, 0

In [47]:
print("shape: {}".format(n.shape))
print("data type: {}".format(n.dtype))
print("dimen: {}".format(n.ndim))
print("size: {}".format(n.itemsize))

shape: (10, 20)
data type: float64
dimen: 2
size: 8


In [49]:
m=np.arange(32).reshape(4,4,2)

m

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [50]:
k=np.arange(10)

k

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
k[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
k[:3]

array([0, 1, 2])

In [53]:
k[::2]

array([0, 2, 4, 6, 8])

In [54]:
k[2::3]

array([2, 5, 8])