In [2]:
import numpy as np

In [4]:
k=np.array([2,8,7,6,2])

k

type(k)

numpy.ndarray

In [5]:
list1=[2,5,8,6,7]
list2=[3,5,9,7,4]

g=list(map(lambda x,y:x*y,list1,list2))

g

[6, 25, 72, 42, 28]

In [36]:
sq=[i**2 for i in list1]

sq

[4, 25, 64, 36, 49]

In [16]:
g=np.array(list1)
k=np.array(list2)
g*k

array([ 6, 25, 72, 42, 28])

In [38]:
sqr=g**2

sqr

array([ 4, 25, 64, 36, 49], dtype=int32)

In [35]:
p=np.arange(1,10)
p

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
l=np.array([[1,2,3],[4,5,6]])
l

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
l[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
l[:1]

array([[1, 2, 3]])

In [23]:
l[2:]

array([], shape=(0, 3), dtype=int32)

In [24]:
l[1:]

array([[4, 5, 6]])

In [25]:
l[1,:]

array([4, 5, 6])

In [26]:
l[1,1]

5

In [27]:
np.ones([3,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.ones([3,4],dtype="int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [29]:
np.zeros([5,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.tile([5,5],7)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [32]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
np.eye(4,4,dtype="int")

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [41]:
np.random.random([5,5])

array([[0.57889467, 0.81683078, 0.52090609, 0.58432924, 0.11732344],
       [0.45847712, 0.1170006 , 0.39120262, 0.69311675, 0.29570293],
       [0.44581846, 0.93038451, 0.19674848, 0.12743065, 0.00267481],
       [0.64735777, 0.54183492, 0.70165688, 0.24072566, 0.98085009],
       [0.05082606, 0.1989271 , 0.6676531 , 0.04524531, 0.57649381]])

In [44]:
np.random.randint(10,20,[4,5])

array([[17, 14, 12, 19, 12],
       [18, 15, 15, 11, 12],
       [16, 17, 19, 11, 10],
       [10, 19, 17, 18, 12]])

In [45]:
np.tile([1,2,3],[2,3])

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [46]:
np.full([5,6],8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [57]:
k=np.linspace(1,10,20)
k

h=np.random.randint(10,20,[5,4])

h

array([[11, 17, 18, 14],
       [10, 17, 11, 19],
       [13, 14, 12, 15],
       [14, 19, 14, 19],
       [16, 10, 16, 13]])

In [59]:
print("shape: {}".format(k.shape))

print("dimension: {}".format(k.ndim))

print("size: {}".format(k.itemsize))

print("data type: {}".format(k.dtype))

shape: (20,)
dimension: 1
size: 8
data type: float64


In [62]:
m=np.arange(24).reshape(4,3,2)

m

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [64]:
m[3,2,1]

23